# Nombre de tu proyecto
name: 'etl_project'
version: '1.0.0'

# Perfil de dbt, asegúrate de que coincida con ~/.dbt/profiles.yml
profile: 'etl_project'

# Configuración de rutas para dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directorios que se limpiarán con `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos en dbt
models:
  etl_project:  # Aplica a todos los modelos en el proyecto
    +materialized: table  # Materialización por defecto en tabla
    customers:
      +materialized: table  # Materialización específica para customers

