# Nombre del proyecto
name: 'jaffle_shop'
version: '1.0.0'

# Perfil de dbt, asegúrate de que coincida con ~/.dbt/profiles.yml
profile: 'jaffle_shop'

# Configuración de rutas para dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directorios que se limpiarán con `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos en dbt
models:
  jaffle_shop:
    +materialized: table  # Todo en 'jaffle_shop' será materializado como tabla

