<<<<<<< HEAD:profiles.yml
# Nombre del proyecto
=======
>>>>>>> 8a259a0 (Actualizando cambios en dbt):dbt_project.yml
name: 'etl_project'
version: '1.0.0'
profile: 'etl_project'

<<<<<<< HEAD:profiles.yml
# Configuración de rutas
=======
# Rutas de directorios en tu proyecto dbt
>>>>>>> 8a259a0 (Actualizando cambios en dbt):dbt_project.yml
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - 'target'
  - 'dbt_packages'

# Configuración de modelos
models:
<<<<<<< HEAD:profiles.yml
  jaffle_shop:
    +schema: "{{ target.schema }}"  # Usa el esquema según el entorno (DEV, QA, PROD)
    
    # Configuración dinámica de materialización según el entorno
    +materialized: "{{ 'view' if target.name == 'Development' else 'incremental' if target.name == 'QA' else 'table' }}"
    
    # Opcional: Configurar unique_key para modelos incrementales
    orders:
      +unique_key: "order_id"

    customers:
      +unique_key: "customer_id"
=======
  etl_project:
    +materialized: table

    # Ejemplo: configuración específica para el modelo "customers"
    customers:
      +materialized: table
>>>>>>> 8a259a0 (Actualizando cambios en dbt):dbt_project.yml
