version: 2

# Definición de las fuentes de datos externas (tablas de Snowflake)
sources:
  - name: JAFFLE_SHOP
    database: RAW                # Asegura que sea la base de datos real en Snowflake
    schema: JAFFLE_SHOP          # Asegura que sea el esquema correcto
    tables:
      - name: CUSTOMERS
      - name: ORDERS

# Definición de los modelos transformados por dbt
models:
  - name: customers
    description: "Tabla transformada de clientes basada en jaffle_shop.customers."
    columns:
      - name: customer_id
        description: "Clave primaria de los clientes."
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: "Fecha de la primera orden del cliente."
      - name: most_recent_order_date
        description: "Fecha de la última orden del cliente."
      - name: number_of_orders
        description: "Número total de órdenes del cliente."
