version: 2

# Definición de las fuentes
sources:
  - name: jaffle_shop               # nombre lógico de la fuente
    database: RAW                   # base de datos real donde están tus tablas
    schema: JAFFLE_SHOP             # esquema real
    tables:
      - name: customers
      - name: orders

# Definición de los modelos (documentación y tests)
models:
  - name: customers
    description: "Tabla transformada de clientes basada en jaffle_shop.customers."
    columns:
      - name: customer_id
        description: "Clave primaria de los clientes."
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: "Fecha de la primera orden del cliente."
      - name: most_recent_order_date
        description: "Fecha de la última orden del cliente."
      - name: number_of_orders
        description: "Número total de órdenes del cliente."
