version: 2

# 🔹 Fuentes (Sources): Definen las tablas en RAW.JAFFLE_SHOP
sources:
  - name: jaffle_shop
    database: RAW  # ✅ Ajusta al nombre correcto en Snowflake
    schema: JAFFLE_SHOP  # ✅ Coincide con lo que ves en Snowflake
    tables:
      - name: CUSTOMERS  # ✅ Usa mayúsculas si Snowflake usa mayúsculas
      - name: ORDERS

# 🔹 Modelos en dbt (Transformaciones en `models/`)
models:
  - name: customers
    description: "Tabla transformada de clientes basada en jaffle_shop.customers."
    columns:
      - name: customer_id
        description: "Clave primaria de los clientes."
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: "Fecha de la primera orden del cliente."
      - name: most_recent_order_date
        description: "Fecha de la última orden del cliente."
      - name: number_of_orders
        description: "Número total de órdenes del cliente."
