version: 2

sources:
  - name: jaffle_shop  # 🔹 Cambiado a minúsculas
    database: raw  # 🔹 Cambiado a minúsculas
    schema: jaffle_shop  # 🔹 Cambiado a minúsculas
    tables:
      - name: customers  # 🔹 Cambiado a minúsculas
      - name: orders  # 🔹 Cambiado a minúsculas
